# Generated by Django 2.1.1 on 2018-09-15 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komitets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='komitet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='komitets.Komitet'),
        ),
    ]
